= JMS Integration Testing Errors

This project exemplifies some errors that may be made during integration testing of JMS code. The examples from
`src/test/java` were inspired from the following four articles from Apache ActiveMQ official documentation and one
about testing JMS listeners:

. https://activemq.apache.org/vm-transport-reference
. https://activemq.apache.org/the-vm-transport-starts-a-broker-before-my-configured-broker-starts
. http://activemq.apache.org/how-to-unit-test-jms-code
. https://activemq.apache.org/how-do-i-embed-a-broker-inside-a-connection
. https://weblog.sourcy.io/2017/03/integration-testing-jms-listeners-with-spring.html

While the content of (classes from) `src/main/java` was inspired from
https://docs.spring.io/spring-framework/docs/5.2.x/spring-framework-reference/integration.html#jms.

Also consider this example from Spring Boot,
https://github.com/spring-projects/spring-integration-samples/blob/master/advanced/advanced-testing-examples/src/test/java/org/springframework/integration/samples/advance/testing/jms/JmsMockTests.java

== The Idea In Short [DRAFT]

In https://activemq.apache.org/vm-transport-reference there is a warning

> Be careful with embedded brokers
>
> If you are using the VM transport and wish to explicitly configure an
> https://activemq.apache.org/how-do-i-embed-a-broker-inside-a-connection[Embedded Broker] there is a chance that you
> could create the JMS connections first before the broker starts up. Currently ActiveMQ will auto-create a broker if
> you use the VM transport and there is not one already configured. (In 5.2 it is possible to use the waitForStart and
> create=false options for the connection uri)
>
> So to work around this if you are using Spring you may wish to use the *depends-on* attribute so that your
> JMS ConnectionFactory depends on the embedded broker to avoid this happening.

while in https://activemq.apache.org/configuring-transports.html

> The first client to use the VM connection will boot an embedded broker. Subsequent connections will attach that the
> same broker. Once all VM connections to the broker have been closed, the embedded broker will automatically shutdown.

These two things if not considered carefully may lead to strange (interesting) results.

== Custom [mis]configured embedded broker

See `JmsQueueSenderDefaultSpringTestConfigIT`.

There are two type of tests here:

. `simpleSend_synchronousSendAndReceive*` - will fail always because the error is obvious;

. `simpleSend_asynchronousSendAndReceive*` - will not fail always.

=== Synchronous calls to send and receive [DRAFT]

The test `simpleSend_synchronousSendAndReceive` from class `JmsQueueSenderCustomTestMisconfigIT` will always fail
because the `receiveAndConvert` method will not find available messages and thus (with JmsTemplate.receiveTimeout = 0)
will block the current thread.

But why there are no messages in the broker? I'll try to explain.

. The `sender.simpleSend` will call `JmsTemplate.send` which in turn will attempt to create a new ActiveMQConnection,
see `public <T> T execute(SessionCallback<T> action, boolean startConnection)` of `JmsTemplate`.

. ActiveMQConnection will try to create a new embedded broker if none is found, see
`public Transport doCompositeConnect(URI location)` of `VMTransportFactory`. Although official documentation lacks the
javadoc for this method I suppose it is named `composite` because beside the connection attempt it also creates
a broker if none found. After the broker creation, a VMTransportServer (server) is created and in the end a
TransportConnector is created which is bind to the server and broker. Three important things from this method:
.. The automatic creation of embedded broker may be controlled by option "create" from `brokerUrl`
(e.g. "vm://localhost?create=false"; will be discussed later);
.. The automatic creation of broker may be delayed by "waitForStart" property (will be discussed later);
.. The creation of the VMTransportServer (which binds with the broker) is done with `disposeOnDisconnect=true`.

. The important moment here that it will call the `server = (VMTransportServer)this.bind(location, true);`, the 2nd
parameter `true`; this parameters controls if the X should stop Y itf threre are no more connections, see
`VMTrasportServer.connect()`
[source,java]
----
if (VMTransportServer.this.connectionCount.decrementAndGet() == 0 && VMTransportServer.this.disposeOnDisconnect) {
    VMTransportServer.this.stop();
}
----
which will stop/remove the broker too.

The whole idea in short. When we send a message we need a broker also when we receive a message we need a broker too.
When we test with an embedded broker, the embedded broker is the same broker that "sends" and "receives" messages. If
we are not careful to configuration aspects we could get into situation when the broker used for sending is stopped
together with the connection and when we try to receive a message a new new broker is created which is "empty" and we
will never receive the message.

=== Asynchronous calls to send and receive

The `simpleSend_asynchronousSendAndReceive` will not fail always. It will fail when the ExecutorService will fail
submit the Callback before `sender.send`. In this case the `sender.send` will succeed to create and close a broker
before `jmsTemplate.receiveAndConvert` attempt. The `simpleSend_asynchronousSendAndReceive_withDetails_twoBrokers`
test illustrates this idea.

== Custom configured embedded broker

See class `JmsQueueSenderIT`.

In https://activemq.apache.org/vm-transport-reference there is a warning

> Be careful with embedded brokers
>
> If you are using the VM transport and wish to explicitly configure an
https://activemq.apache.org/how-do-i-embed-a-broker-inside-a-connection[Embedded Broker] there is a chance that you
could create the JMS connections first before the broker starts up. Currently ActiveMQ will auto-create a broker if
you use the VM transport and there is not one already configured. (In 5.2 it is possible to use the waitForStart and
create=false options for the connection uri)
>
> So to work around this if you are using Spring you may wish to use the *depends-on* attribute so that your
JMS ConnectionFactory depends on the embedded broker to avoid this happening.

We use the recommended solution in the nested `TestConfiguration` of the `JmsQueueSenderIT` test class:

[source, java]
----
@Bean
public BrokerService brokerService() throws Exception {
    BrokerService broker = new BrokerService();
    broker.setPersistent(false);
    broker.addConnector("vm://localhost");
    return broker;
}

@Bean
@DependsOn("brokerService")
public ActiveMQConnectionFactory connectionFactory() {
    ActiveMQConnectionFactory activeMQConnectionFactory = new ActiveMQConnectionFactory();
    activeMQConnectionFactory.setBrokerURL("vm://localhost?create=false");
    return activeMQConnectionFactory;
}
----

With this configuration, the embedded broker is not created by JMS ConnectionFactory but before it, via
`BrokerService.addConnector` call. In turn `BrokerService.addConnector` calls `VMTransportFactory.doBind(location)`
which creates a `new VMTransportServer(location, false)` i.e. with `disposeOnDisconnect=true`. This setting makes
broker "immune" (its not stopped when a JMS connection is closed) to the errors exemplified in
`JmsQueueSenderCustomTestMisconfigIT`.

== Spring default JMS test configuration

See class `JmsQueueSenderDefaultSpringTestConfigIT`.

By default, Spring creates `JmsTemplate` singleton with `CachingConnectionFactory` as ConnectionFactory. This class
uses `ActiveMQConnectionFactory` to create connections, thus the embedded broker will be created automatically,
if none found, together with a `VMTransportServer` having `disposeOnDisconnect=true`. Therefore we should expect that
at the end of `JmsTemplate.send` the broker will be stopped but this will not happen because `CachingConnectionFactory`
inherits from `SingleConnectionFactory` which does not stop the server at `Connection.close`:

> A JMS ConnectionFactory adapter that returns the same Connection from all createConnection() calls, and ignores
calls to Connection.close().
> -- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jms/connection/SingleConnectionFactory.html[Class SingleConnectionFactory official documentation]

Some findings:

* The actual value of embedded `brokerUrl` is taken from `spring.activemq.broker-url` property, if its not present,
then `"vm://localhost?broker.persistent=false"` is used, see `determineBrokerUrl()` from
`ActiveMQConnectionFactoryFactory`:

[source,java]
----
String determineBrokerUrl() {
    if (this.properties.getBrokerUrl() != null) {
        return this.properties.getBrokerUrl();
    } else {
        return this.properties.isInMemory() ? "vm://localhost?broker.persistent=false" : "tcp://localhost:61616";
    }
}
----

Thus we can set the url for tests in `test/resources/application.properties`.